require:
  - rubocop-rails

AllCops:
  Exclude:
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/*
    - config/*
    - bin/*
    - vendor/**/*
  TargetRubyVersion: 2.6

Metrics/LineLength:
  Max: 120

Naming/AsciiIdentifiers:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
